[package]
name = "archapp_xc"
version = "0.0.1-a.dev.4"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.126"
serde_json = "1.0.64"
async-channel = "1.6"
err = { path = "../err" }
netpod = { path = "../netpod" }
