[package]
name = "scyllaconn"
version = "0.0.1"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[lib]
path = "src/scyllaconn.rs"

[dependencies]
futures-util = "0.3.24"
async-channel = "1.9.0"
scylla = "0.11.0"
err = { path = "../err" }
netpod = { path = "../netpod" }
query = { path = "../query" }
items_0 = { path = "../items_0" }
items_2 = { path = "../items_2" }
