[workspace]
members = ["daqbuffer", "h5out", "archapp", "archapp_xc", "archapp_wrap", "items", "nodenet", "httpclient"]

[profile.release]
debug = 1
opt-level = 1
#overflow-checks = true
#debug-assertions = true
lto = "off"
codegen-units = 40

[patch.crates-io]
tokio = { git = "https://github.com/dominikwerder/tokio", branch = "maxbuf" }
