[package]
name = "netpod"
version = "0.0.1-a.0"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
#serde_derive = "1.0"
async-channel = "1.6"
bytes = "1.0.1"
futures-core = "0.3.12"
err = { path = "../err" }
