[package]
name = "parse"
version = "0.0.2"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
humantime-serde = "1.1"
tokio = { version = "1.28.2", features = ["fs"] }
chrono = { version = "0.4.26", features = ["serde"] }
bytes = "1.4"
byteorder = "1.4"
hex = "0.4.3"
nom = "7.1.3"
err = { path = "../err" }
netpod = { path = "../netpod" }
