name: build-daqbuffer-wf
on:
  - push
jobs:
  build-daqbuffer-job:
    runs-on: ubuntu-latest
    container:
      image: "ugnvc/psi:daqbufferbuild-0.0.6"
    steps:
      - uses: actions/checkout@v2
      - run: /usr/bin/df -h
      - run: pwd
      - run: ls -ltra
      - run: ls -la /
      - run: ls -la /github
      - run: ls -la /github/home
      - run: ls -la /github/workflow
      - run: ls -la /root
      - run: echo "${HOME}"
      - run: echo "${PATH}"
      - run: source /root/.cargo/env
      - run: echo "${PATH}"
      - run: "/bin/bash -c 'echo $PATH && source /root/.cargo/env && echo $PATH && ls -la /root/.cargo/bin'"
      - run: "/bin/bash -c 'PATH=\"/root/.cargo/bin:$PATH\" && echo $PATH && cargo --version'"
      - run: "/bin/bash -c 'echo $PATH && cargo --version'"
