name: build-daqbuffer-wf
on:
  - push
jobs:
  build-daqbuffer-job:
    runs-on: ubuntu-latest
    container:
      image: "ugnvc/psi:daqbufferbuild-0.0.6"
    steps:
      - uses: actions/checkout@v2
      - run: /usr/bin/df -h
      - run: pwd
      - run: ls -ltra
      - run: ls -la /
      - run: ls -la /github
      - run: ls -la /github/home
      - run: cargo build --release
