name: build-daqbuffer-wf
on:
  - push
jobs:
  build-daqbuffer-job:
    #runs-on: "docker.io/ugnvc/psi:daqbufferbuild-0.0.6"
    runs-on: ubuntu-latest
    container:
      image: "docker.io/ugnvc/psi:daqbufferbuild-0.0.6"
      volumes:
        - ".:/m1"
    steps:
      - uses: actions/checkout@v2
      - run: ls -ltra
      - run: which docker
      - run: ls -la /m1
